### PR TITLE
Menu bar modifications

### PR DESCRIPTION
**Pull request by davidli43**
- switched menu bar icon
- added progress bar carousel
- added boostrap css, which may cause style changes that needs to be fixed if reported

### CODE REVIEW

**Comment by milanocookies93** [comment]
Merge conflicts, please rebase.

**Comment by davidli43** [comment]
I think it's fixed now.
I did a "git fetch upstream"
then "git rebase upstream/master" and resolved all conflicts

**Comment by milanocookies93** [comment]
Still have merge conflicts

**Comment by davidli43** [comment]
I'm not quite sure what I did wrong, I followed the update steps in https://robots.thoughtbot.com/keeping-a-github-fork-updated. Now when I enter "git rebase upstream/master", it outputs "Current branch master is up to date". If there are still problems, I'll seek help later.
Sorry for the trouble.

**Pull request closed without merging**
